[package]
name = "daisy"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "daisy"

[build-dependencies]
lalrpop = "0.22.1"

[dependencies.lalrpop-util]
version = "0.22.1"
features = ["lexer", "unicode"]
