[package]
name = "daisy"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "daisy"

[build-dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"

[dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
